import 'package:drift/drift.dart';
import '../database/database.dart';
import '../../core/enums/app_enums.dart';

/// محرك أتمتة المهام اليومية والخط الزمني (TaskSyncService & TimelineEngine)
/// يربط الجلسات، التذكيرات، ومراحل تأسيس الشركات بجدول الأعمال اليومية ويسجل كل الأحداث في الخط الزمني.
class TaskSyncService {
  final AppDatabase db;
  TaskSyncService(this.db);

  // ---------------------------------------------------------------------------
  // 1. أتمتة جلسات المحاكم (Case Sessions Automation)
  // ---------------------------------------------------------------------------

  /// حفظ جلسة جديدة، ترحيل موعدها القادم تلقائياً للأعمال اليومية، وتسجيل الحدث في الخط الزمني
  Future<int> syncSessionToDailyTask({
    required CaseSessionsCompanion session,
    required String caseTitle,
    required String userRef,
  }) async {
    return await db.transaction(() async {
      // 1. حفظ الجلسة في جدول CaseSessions
      final sessionId = await db.into(db.caseSessions).insert(session);
      final int caseId = session.caseId.value;

      // 2. إذا كان هناك موعد جلسة قادمة، يتم توليد مهمة يومية مجدولة تلقائياً
      if (session.nextSessionDate.present && session.nextSessionDate.value != null) {
        final nextDate = session.nextSessionDate.value!;
        
        await db.into(db.dailyTasks).insert(
          DailyTasksCompanion.insert(
            taskType: 'session',
            title: 'جلسة قادمة: $caseTitle (${session.nextAction.value ?? "مرافعة / تدقيق"})',
            taskDate: nextDate,
            taskTime: session.sessionTime,
            status: Value(LifecycleStatus.scheduled.index),
            assignedTo: Value(userRef),
            priority: Value(TaskPriority.high.index),
            sourceType: const Value('cases'),
            sourceId: Value(caseId),
            isAutoGenerated: const Value(true),
            notes: session.notes,
          ),
        );

        // تحديث التاريخ السريع Cached في جدول Cases
        await (db.update(db.cases)..where((t) => t.id.equals(caseId))).write(
          CasesCompanion(
            nextSessionDate: Value(nextDate),
            updatedAt: Value(DateTime.now()),
          ),
        );
      }

      // 3. تسجيل الحدث في الخط الزمني الشامل (TimelineEvents)
      await db.into(db.timelineEvents).insert(
        TimelineEventsCompanion.insert(
          entityType: EntityType.caseEntity.index,
          entityId: caseId,
          eventType: 'session_scheduled',
          eventDate: Value(session.sessionDate.value),
          description: 'تم انعقاد جلسة قضائية وتحديد الموعد/الإجراء القادم: ${session.nextAction.value ?? "غير محدد"}',
          userRef: Value(userRef),
        ),
      );

      return sessionId;
    });
  }

  // ---------------------------------------------------------------------------
  // 2. أتمتة تذكيرات العقود (Contract Reminders Automation)
  // ---------------------------------------------------------------------------

  /// ترحيل تذكير العقد (انتهاء / تجديد) إلى جدول الأعمال اليومية للمكتب
  Future<void> syncContractReminder({
    required ContractRemindersCompanion reminder,
    required String contractTitle,
    required int contractId,
  }) async {
    return await db.transaction(() async {
      final reminderId = await db.into(db.contractReminders).insert(reminder);
      
      if (reminder.reminderDate.value.isAfter(DateTime.now().subtract(const Duration(days: 1)))) {
        final taskId = await db.into(db.dailyTasks).insert(
          DailyTasksCompanion.insert(
            taskType: 'contract_reminder',
            title: 'تذكير عقد: $contractTitle (${reminder.reminderType.value})',
            taskDate: reminder.reminderDate.value,
            status: Value(LifecycleStatus.scheduled.index),
            priority: Value(TaskPriority.high.index),
            sourceType: const Value('contracts'),
            sourceId: Value(contractId),
            isAutoGenerated: const Value(true),
            notes: reminder.reminderNote,
          ),
        );

        // ربط معرف المهمة المولد بسجل التذكير
        await (db.update(db.contractReminders)..where((t) => t.id.equals(reminderId))).write(
          ContractRemindersCompanion(autoTaskId: Value(taskId)),
        );
      }
    });
  }

  // ---------------------------------------------------------------------------
  // 3. أتمتة مراحل تأسيس الشركات (Company Phases Automation)
  // ---------------------------------------------------------------------------

  /// ترحيل موعد إنجاز مرحلة تأسيس شركة إلى المهام اليومية
  Future<int> syncCompanyPhase({
    required CompanyPhasesCompanion phase,
    required String companyName,
    required int companyId,
    required String userRef,
  }) async {
    return await db.transaction(() async {
      final phaseId = await db.into(db.companyPhases).insert(phase);

      if (phase.scheduledDate.present && phase.scheduledDate.value != null) {
        await db.into(db.dailyTasks).insert(
          DailyTasksCompanion.insert(
            taskType: 'company_phase',
            title: 'مرحلة تأسيس [$companyName]: ${phase.phaseName.value}',
            taskDate: phase.scheduledDate.value!,
            status: Value(LifecycleStatus.scheduled.index),
            assignedTo: Value(userRef),
            priority: Value(TaskPriority.normal.index),
            sourceType: const Value('companies'),
            sourceId: Value(companyId),
            isAutoGenerated: const Value(true),
            notes: phase.notes,
          ),
        );
      }

      await db.into(db.timelineEvents).insert(
        TimelineEventsCompanion.insert(
          entityType: EntityType.company.index,
          entityId: companyId,
          eventType: 'phase_added',
          eventDate: Value(DateTime.now()),
          description: 'تم إضافة مرحلة تأسيس جديدة: ${phase.phaseName.value}',
          userRef: Value(userRef),
        ),
      );

      return phaseId;
    });
  }

  // ---------------------------------------------------------------------------
  // 4. دورة حياة المهام: التأجيل والإلغاء مع حفظ السجلات (Postpone & Cancel)
  // ---------------------------------------------------------------------------

  /// تأجيل مهمة أو جلسة قضائية إلى موعد جديد مع توثيق السبب والاحتفاظ بالتاريخ السابق
  Future<void> postponeTask({
    required int taskId,
    required DateTime newDate,
    required String reason,
    required String userRef,
  }) async {
    await db.transaction(() async {
      final oldTask = await (db.select(db.dailyTasks)..where((t) => t.id.equals(taskId))).getSingle();

      // 1. تحديث المهمة القديمة إلى حالة "مؤجلة"
      await (db.update(db.dailyTasks)..where((t) => t.id.equals(taskId))).write(
        DailyTasksCompanion(
          status: Value(LifecycleStatus.postponed.index),
          updatedAt: Value(DateTime.now()),
        ),
      );

      // 2. إدراج سجل في تاريخ المهام (TaskHistory)
      await db.into(db.taskHistory).insert(
        TaskHistoryCompanion.insert(
          taskId: taskId,
          action: 'postponed',
          reason: Value(reason),
          notes: Value('تم التأجيل من موعد ${oldTask.taskDate.toString().substring(0, 10)} إلى ${newDate.toString().substring(0, 10)} بواسطة $userRef'),
        ),
      );

      // 3. إنشاء مهمة جديدة مجدولة بالموعد الجديد
      await db.into(db.dailyTasks).insert(
        DailyTasksCompanion.insert(
          taskType: oldTask.taskType,
          title: oldTask.title,
          taskDate: newDate,
          taskTime: Value(oldTask.taskTime),
          status: Value(LifecycleStatus.scheduled.index),
          assignedTo: Value(userRef),
          priority: Value(oldTask.priority),
          sourceType: Value(oldTask.sourceType),
          sourceId: Value(oldTask.sourceId),
          isAutoGenerated: Value(oldTask.isAutoGenerated),
          notes: Value('مرحّلة من تأجيل سابق. سبب التأجيل: $reason'),
        ),
      );

      // 4. توثيق الحدث في الخط الزمني إذا كانت المهمة مرتبطة بكيان معين
      if (oldTask.sourceType != null && oldTask.sourceId != null) {
        final entityType = _parseEntityType(oldTask.sourceType!);
        if (entityType != null) {
          await db.into(db.timelineEvents).insert(
            TimelineEventsCompanion.insert(
              entityType: entityType.index,
              entityId: oldTask.sourceId!,
              eventType: 'task_postponed',
              eventDate: Value(DateTime.now()),
              description: 'تم تأجيل موعد [${oldTask.title}] إلى ${newDate.toString().substring(0, 10)} - السبب: $reason',
              userRef: Value(userRef),
            ),
          );
        }
      }
    });
  }

  /// إلغاء مهمة مع حفظ سبب الإلغاء في السجل
  Future<void> cancelTask({
    required int taskId,
    required String reason,
    required String userRef,
  }) async {
    await db.transaction(() async {
      final task = await (db.select(db.dailyTasks)..where((t) => t.id.equals(taskId))).getSingle();

      await (db.update(db.dailyTasks)..where((t) => t.id.equals(taskId))).write(
        DailyTasksCompanion(
          status: Value(LifecycleStatus.cancelled.index),
          updatedAt: Value(DateTime.now()),
        ),
      );

      await db.into(db.taskHistory).insert(
        TaskHistoryCompanion.insert(
          taskId: taskId,
          action: 'cancelled',
          reason: Value(reason),
          notes: Value('تم الإلغاء بواسطة $userRef'),
        ),
      );

      if (task.sourceType != null && task.sourceId != null) {
        final entityType = _parseEntityType(task.sourceType!);
        if (entityType != null) {
          await db.into(db.timelineEvents).insert(
            TimelineEventsCompanion.insert(
              entityType: entityType.index,
              entityId: task.sourceId!,
              eventType: 'task_cancelled',
              eventDate: Value(DateTime.now()),
              description: 'تم إلغاء [${task.title}] - السبب: $reason',
              userRef: Value(userRef),
            ),
          );
        }
      }
    });
  }

  EntityType? _parseEntityType(String source) {
    switch (source) {
      case 'cases':
        return EntityType.caseEntity;
      case 'contracts':
        return EntityType.contract;
      case 'companies':
        return EntityType.company;
      case 'admin_procedures':
        return EntityType.adminProcedure;
      default:
        return null;
    }
  }
}
